/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'pendingVerification' : null } |
  { 'closed' : null } |
  { 'active' : null } |
  { 'suspended' : null };
export type ApplicationStatus = { 'cancelled' : null } |
  { 'submitted' : null } |
  { 'underReview' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface AuditEntry {
  'id' : string,
  'initiator' : Principal,
  'actionType' : string,
  'entityId' : string,
  'timestamp' : bigint,
  'details' : string,
  'entityType' : string,
}
export interface BudgetRange { 'minBudget' : number, 'maxBudget' : number }
export interface Conversation {
  'id' : string,
  'participantA' : Principal,
  'participantB' : Principal,
  'lastMessageTimestamp' : bigint,
  'messages' : Array<Message>,
}
export interface ConversationSummary {
  'id' : string,
  'participantA' : Principal,
  'participantB' : Principal,
  'lastMessageTimestamp' : bigint,
  'unreadMessagesCount' : bigint,
}
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface DashboardStats {
  'activeDisputes' : bigint,
  'recentApplications' : Array<
    {
      'id' : string,
      'status' : string,
      'created' : bigint,
      'titleNumber' : string,
    }
  >,
  'verifiedOwners' : bigint,
  'estimatedTotalLandValue' : number,
  'totalRegisteredTitles' : bigint,
  'pendingTransactions' : bigint,
}
export interface DemandHeatMapPoint {
  'demandScore' : bigint,
  'location' : string,
  'coordinates' : [] | [Coordinates],
}
export interface DisputeEvidence {
  'id' : string,
  'description' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'fileId' : string,
  'timestamp' : bigint,
  'uploadedBy' : Principal,
  'disputeId' : string,
}
export type DisputeStatus = { 'resolved' : null } |
  { 'underReview' : null } |
  { 'open' : null };
export interface DisputeTimelineEvent {
  'id' : string,
  'initiator' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'eventType' : string,
  'disputeId' : string,
  'evidenceIds' : Array<string>,
}
export interface DisputeView {
  'id' : string,
  'status' : DisputeStatus,
  'created' : Time,
  'initiator' : Principal,
  'propertyId' : string,
  'updated' : Time,
  'comments' : Array<string>,
  'reason' : string,
}
export type DomainRole = { 'admin' : null } |
  { 'citizen' : null } |
  { 'landOfficer' : null };
export type ExternalBlob = Uint8Array;
export interface GeneratedPropertyReport {
  'content' : string,
  'generatedAt' : bigint,
  'reportId' : string,
}
export interface IdentityFields {
  'dateOfBirth' : string,
  'nationalId' : string,
  'ethnicity' : string,
  'passportNumber' : string,
}
export interface InfrastructureProject {
  'id' : string,
  'status' : ProjectStatus,
  'created' : Time,
  'name' : string,
  'details' : string,
  'location' : string,
}
export interface InfrastructureTimelineItem {
  'id' : string,
  'region' : string,
  'status' : string,
  'endDate' : [] | [bigint],
  'name' : string,
  'type' : string,
  'description' : string,
  'impactRadius' : number,
  'startDate' : bigint,
}
export interface InvestmentInput {
  'investmentYears' : bigint,
  'buyingPriceKES' : number,
  'annualGrowthRatePercent' : number,
}
export interface InvestmentResult {
  'profitKES' : number,
  'projectedValueKES' : number,
  'roiPercent' : number,
  'breakEvenYears' : number,
  'profitPercent' : number,
}
export interface LandApplicationView {
  'id' : string,
  'status' : ApplicationStatus,
  'created' : Time,
  'titleNumber' : string,
  'owner' : Principal,
  'area' : [] | [bigint],
  'updated' : Time,
  'location' : string,
  'attachments' : Array<ExternalBlob>,
}
export interface MarketAnalytics {
  'pricesByRegion' : Array<[string, number]>,
  'activeListings' : bigint,
  'appreciationRates' : Array<[string, number]>,
  'topRegions' : Array<string>,
}
export interface MarketSummary {
  'numTransactions' : bigint,
  'averagePrice' : number,
  'location' : string,
}
export interface MarketTrend {
  'id' : string,
  'created' : Time,
  'price' : number,
  'location' : string,
}
export interface MarketTrendData {
  'demandScore' : bigint,
  'priceTrend' : Array<PricePoint>,
  'location' : string,
}
export interface Message {
  'id' : string,
  'content' : string,
  'read' : boolean,
  'sender' : Principal,
  'timestamp' : bigint,
  'receiver' : Principal,
}
export type MotionPreference = { 'advanced' : null } |
  { 'default' : null } |
  { 'reduced' : null };
export interface Notification {
  'id' : string,
  'read' : boolean,
  'recipient' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface NotificationFeedItem {
  'id' : string,
  'title' : string,
  'body' : string,
  'link' : [] | [string],
  'read' : boolean,
  'type' : string,
  'timestamp' : bigint,
}
export interface NotificationPreferences {
  'sms' : boolean,
  'push' : boolean,
  'criticalAlertsOnly' : boolean,
  'email' : boolean,
}
export interface PortfolioSummary {
  'riskDistribution' : { 'low' : bigint, 'high' : bigint, 'medium' : bigint },
  'annualGrowthRate' : number,
  'totalEstimatedValue' : number,
  'properties' : Array<Property>,
}
export interface Preferences {
  'notifyInfrastructureUpdates' : boolean,
  'riskTolerance' : RiskType,
  'notifyNewListings' : boolean,
  'notifyPriceDrops' : boolean,
  'aiPersonalization' : {
    'growthExpectation' : bigint,
    'preferredLandType' : string,
    'riskAppetite' : RiskType,
    'investmentGoals' : Array<string>,
    'budgetRange' : BudgetRange,
  },
  'notifyMarketTrends' : boolean,
  'notifyDisputes' : boolean,
  'preferredRegions' : Array<string>,
}
export interface PricePoint { 'timestamp' : Time, 'price' : number }
export interface PrivacyPreferences {
  'allowDataCollection' : boolean,
  'shareLocation' : boolean,
  'showPublicProfile' : boolean,
}
export type ProjectStatus = { 'completed' : null } |
  { 'planned' : null } |
  { 'ongoing' : null };
export interface Property {
  'id' : string,
  'status' : PropertyStatus,
  'created' : Time,
  'value' : number,
  'titleNumber' : string,
  'owner' : Principal,
  'area' : number,
  'updated' : Time,
  'location' : string,
}
export interface PropertyReport {
  'id' : string,
  'created' : Time,
  'content' : string,
  'propertyId' : string,
  'author' : Principal,
}
export type PropertyStatus = { 'active' : null } |
  { 'disputed' : null } |
  { 'pending' : null } |
  { 'sold' : null };
export interface RiskSummary {
  'fraudAlertCount' : bigint,
  'highRiskProperties' : Array<string>,
  'recentDisputes' : Array<DisputeView>,
  'riskScore' : number,
}
export type RiskType = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface SavedProperty {
  'id' : string,
  'userId' : Principal,
  'propertyId' : string,
  'savedAt' : Time,
}
export interface SendMessageResponse { 'message' : string, 'success' : boolean }
export type ThemePreference = { 'dark' : null } |
  { 'futuristic' : null } |
  { 'light' : null };
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'status' : TransactionStatus,
  'date' : Time,
  'propertyId' : string,
  'seller' : Principal,
  'buyer' : Principal,
  'price' : number,
}
export type TransactionStage = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'recorded' : null } |
  { 'stampDuty' : null } |
  { 'proposed' : null } |
  { 'escrow' : null };
export interface TransactionStageEntry {
  'initiator' : Principal,
  'stage' : TransactionStage,
  'notes' : string,
  'timestamp' : bigint,
}
export type TransactionStatus = { 'disputed' : null } |
  { 'initiated' : null } |
  { 'completed' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'notifications' : NotificationPreferences,
  'themePreference' : ThemePreference,
  'privacy' : PrivacyPreferences,
  'motionPreference' : MotionPreference,
}
export interface Valuation {
  'id' : string,
  'status' : ValuationStatus,
  'created' : Time,
  'value' : number,
  'date' : Time,
  'valuer' : Principal,
  'propertyId' : string,
}
export interface ValuationInput {
  'roadAccess' : boolean,
  'landSizeAcres' : number,
  'nearbyAmenities' : Array<string>,
  'location' : string,
}
export interface ValuationResult {
  'comparableProperties' : Array<string>,
  'growthForecastPercent' : number,
  'confidenceScore' : number,
  'estimatedValueKES' : number,
  'investmentPotential' : string,
}
export type ValuationStatus = { 'disputed' : null } |
  { 'pending' : null } |
  { 'approved' : null };
export interface VerificationRecord {
  'status' : VerificationStatus,
  'officerId' : Principal,
  'notes' : string,
  'timestamp' : bigint,
}
export type VerificationStatus = { 'pendingReview' : null } |
  { 'verified' : null } |
  { 'unverified' : null } |
  { 'rejected' : null };
export interface VerifiedUserProfile {
  'accountStatus' : AccountStatus,
  'emailVerified' : boolean,
  'name' : string,
  'role' : DomainRole,
  'riskType' : RiskType,
  'identityFields' : [] | [IdentityFields],
  'idDocument' : [] | [ExternalBlob],
  'photo' : [] | [ExternalBlob],
  'phoneVerified' : boolean,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addDisputeEvidence' : ActorMethod<
    [string, string, string, bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'advanceTransactionStage' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveApplication' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateInvestment' : ActorMethod<[InvestmentInput], InvestmentResult>,
  'calculateValuation' : ActorMethod<
    [ValuationInput],
    { 'ok' : ValuationResult } |
      { 'err' : string }
  >,
  'cancelApplication' : ActorMethod<[string], undefined>,
  'checkApplicationStatus' : ActorMethod<
    [Principal],
    Array<LandApplicationView>
  >,
  'clearCallerPreferences' : ActorMethod<[], undefined>,
  'clearSearchCounts' : ActorMethod<[], undefined>,
  'clearUserSettings' : ActorMethod<[], undefined>,
  'createApplication' : ActorMethod<[string, [] | [bigint], string], string>,
  'createDispute' : ActorMethod<[DisputeView], undefined>,
  'createInfrastructureProject' : ActorMethod<
    [InfrastructureProject],
    undefined
  >,
  'createMarketTrend' : ActorMethod<[MarketTrend], undefined>,
  'createNotification' : ActorMethod<[Notification], undefined>,
  'createProperty' : ActorMethod<[Property], undefined>,
  'createPropertyReport' : ActorMethod<[PropertyReport], undefined>,
  'createSavedProperty' : ActorMethod<[SavedProperty], undefined>,
  'createTransaction' : ActorMethod<[Transaction], undefined>,
  'createValuation' : ActorMethod<[Valuation], undefined>,
  'deleteConversation' : ActorMethod<[string], undefined>,
  'deleteDispute' : ActorMethod<[string], undefined>,
  'deleteInfrastructureProject' : ActorMethod<[string], undefined>,
  'deleteMarketTrend' : ActorMethod<[string], undefined>,
  'deleteNotification' : ActorMethod<[string], undefined>,
  'deleteProperty' : ActorMethod<[string], undefined>,
  'deletePropertyReport' : ActorMethod<[string], undefined>,
  'deleteSavedProperty' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'deleteValuation' : ActorMethod<[string], undefined>,
  'exportAuditCsv' : ActorMethod<[[] | [string]], string>,
  'generatePropertyReport' : ActorMethod<
    [string],
    { 'ok' : GeneratedPropertyReport } |
      { 'err' : string }
  >,
  'getAllCoordinates' : ActorMethod<[], Array<[string, Coordinates]>>,
  'getAllMarketTrends' : ActorMethod<[], Array<MarketTrendData>>,
  'getApplicationStatus' : ActorMethod<[string], ApplicationStatus>,
  'getApplications' : ActorMethod<
    [Array<Principal>],
    Array<LandApplicationView>
  >,
  'getApplicationsByStatusInternal' : ActorMethod<
    [ApplicationStatus],
    Array<LandApplicationView>
  >,
  'getAuditLog' : ActorMethod<
    [[] | [string], [] | [string], bigint],
    Array<AuditEntry>
  >,
  'getCallerPreferences' : ActorMethod<[], Preferences>,
  'getCallerUserProfile' : ActorMethod<[], [] | [VerifiedUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerUserSettings' : ActorMethod<[], UserSettings>,
  'getConversation' : ActorMethod<[Principal], [] | [Conversation]>,
  'getConversationMessages' : ActorMethod<[Principal], Array<Message>>,
  'getConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDemandHeatMapPoints' : ActorMethod<[], Array<DemandHeatMapPoint>>,
  'getDemandScore' : ActorMethod<[string], bigint>,
  'getDispute' : ActorMethod<[string], [] | [DisputeView]>,
  'getDisputeEvidence' : ActorMethod<
    [string],
    { 'ok' : Array<DisputeEvidence> } |
      { 'err' : string }
  >,
  'getDisputeTimeline' : ActorMethod<
    [string],
    { 'ok' : Array<DisputeTimelineEvent> } |
      { 'err' : string }
  >,
  'getInfrastructureProject' : ActorMethod<
    [string],
    [] | [InfrastructureProject]
  >,
  'getInfrastructureTimeline' : ActorMethod<
    [[] | [string]],
    Array<InfrastructureTimelineItem>
  >,
  'getInvestmentPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getLocationCoordinates' : ActorMethod<[string], [] | [Coordinates]>,
  'getMarketAnalytics' : ActorMethod<[[] | [string]], MarketAnalytics>,
  'getMarketSummary' : ActorMethod<[string], [] | [MarketSummary]>,
  'getMarketTrend' : ActorMethod<[string], [] | [MarketTrend]>,
  'getMarketplaceListings' : ActorMethod<
    [[] | [boolean], [] | [number], [] | [number]],
    Array<Property>
  >,
  'getNotification' : ActorMethod<[string], [] | [Notification]>,
  'getNotificationFeed' : ActorMethod<[bigint], Array<NotificationFeedItem>>,
  'getPriceTrend' : ActorMethod<[string], Array<PricePoint>>,
  'getProperty' : ActorMethod<[string], [] | [Property]>,
  'getPropertyReport' : ActorMethod<[string], [] | [PropertyReport]>,
  'getRiskIntelligenceSummary' : ActorMethod<[[] | [string]], RiskSummary>,
  'getSavedProperty' : ActorMethod<[string], [] | [SavedProperty]>,
  'getTitleVerificationHistory' : ActorMethod<
    [string],
    { 'ok' : Array<VerificationRecord> } |
      { 'err' : string }
  >,
  'getTopSearches' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getTransaction' : ActorMethod<[string], [] | [Transaction]>,
  'getTransactionStageHistory' : ActorMethod<
    [string],
    { 'ok' : Array<TransactionStageEntry> } |
      { 'err' : string }
  >,
  'getUserConversations' : ActorMethod<[Principal], Array<ConversationSummary>>,
  'getUserPreferences' : ActorMethod<[Principal], Preferences>,
  'getUserProfile' : ActorMethod<[Principal], [] | [VerifiedUserProfile]>,
  'getUserSettings' : ActorMethod<[Principal], UserSettings>,
  'getValuation' : ActorMethod<[string], [] | [Valuation]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDisputes' : ActorMethod<[], Array<DisputeView>>,
  'listInfrastructureProjects' : ActorMethod<[], Array<InfrastructureProject>>,
  'listMarketTrends' : ActorMethod<[], Array<MarketTrend>>,
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  'listProperties' : ActorMethod<[], Array<Property>>,
  'listPropertyReports' : ActorMethod<[], Array<PropertyReport>>,
  'listSavedProperties' : ActorMethod<[], Array<SavedProperty>>,
  'listTransactions' : ActorMethod<[], Array<Transaction>>,
  'listValuations' : ActorMethod<[], Array<Valuation>>,
  'markAllMessagesAsRead' : ActorMethod<[string], undefined>,
  'markNotificationRead' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'officerVerifyTitle' : ActorMethod<
    [string, VerificationStatus, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordSearch' : ActorMethod<[string], undefined>,
  'rejectApplication' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[VerifiedUserProfile], undefined>,
  'searchApplicationByTitleNumber' : ActorMethod<
    [string],
    Array<LandApplicationView>
  >,
  'searchApplicationsByLocation' : ActorMethod<
    [string],
    Array<LandApplicationView>
  >,
  'searchApplicationsByTitleNumber' : ActorMethod<
    [string],
    Array<LandApplicationView>
  >,
  'searchUsers' : ActorMethod<
    [string],
    Array<[Principal, VerifiedUserProfile]>
  >,
  'sendMessage' : ActorMethod<[Principal, string], SendMessageResponse>,
  'setCallerPreferences' : ActorMethod<[Preferences], undefined>,
  'setDemandScore' : ActorMethod<[string, bigint], undefined>,
  'setLocationCoordinates' : ActorMethod<[string, number, number], undefined>,
  'setMarketSummary' : ActorMethod<[string, MarketSummary], undefined>,
  'setPriceTrend' : ActorMethod<[string, Array<PricePoint>], undefined>,
  'submitApplication' : ActorMethod<[string], undefined>,
  'submitForVerification' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCallerUserSettings' : ActorMethod<[UserSettings], UserSettings>,
  'updateDispute' : ActorMethod<[DisputeView], undefined>,
  'updateInfrastructureProject' : ActorMethod<
    [InfrastructureProject],
    undefined
  >,
  'updateMarketTrend' : ActorMethod<[MarketTrend], undefined>,
  'updateNotification' : ActorMethod<[Notification], undefined>,
  'updateProperty' : ActorMethod<[Property], undefined>,
  'updatePropertyReport' : ActorMethod<[PropertyReport], undefined>,
  'updateSavedProperty' : ActorMethod<[SavedProperty], undefined>,
  'updateTransaction' : ActorMethod<[Transaction], undefined>,
  'updateValuation' : ActorMethod<[Valuation], undefined>,
  'uploadAttachment' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];