/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvestmentInput = IDL.Record({
  'investmentYears' : IDL.Nat,
  'buyingPriceKES' : IDL.Float64,
  'annualGrowthRatePercent' : IDL.Float64,
});
export const InvestmentResult = IDL.Record({
  'profitKES' : IDL.Float64,
  'projectedValueKES' : IDL.Float64,
  'roiPercent' : IDL.Float64,
  'breakEvenYears' : IDL.Float64,
  'profitPercent' : IDL.Float64,
});
export const ValuationInput = IDL.Record({
  'roadAccess' : IDL.Bool,
  'landSizeAcres' : IDL.Float64,
  'nearbyAmenities' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const ValuationResult = IDL.Record({
  'comparableProperties' : IDL.Vec(IDL.Text),
  'growthForecastPercent' : IDL.Float64,
  'confidenceScore' : IDL.Float64,
  'estimatedValueKES' : IDL.Float64,
  'investmentPotential' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'submitted' : IDL.Null,
  'underReview' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LandApplicationView = IDL.Record({
  'id' : IDL.Text,
  'status' : ApplicationStatus,
  'created' : Time,
  'titleNumber' : IDL.Text,
  'owner' : IDL.Principal,
  'area' : IDL.Opt(IDL.Nat),
  'updated' : Time,
  'location' : IDL.Text,
  'attachments' : IDL.Vec(ExternalBlob),
});
export const DisputeStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'underReview' : IDL.Null,
  'open' : IDL.Null,
});
export const DisputeView = IDL.Record({
  'id' : IDL.Text,
  'status' : DisputeStatus,
  'created' : Time,
  'initiator' : IDL.Principal,
  'propertyId' : IDL.Text,
  'updated' : Time,
  'comments' : IDL.Vec(IDL.Text),
  'reason' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const InfrastructureProject = IDL.Record({
  'id' : IDL.Text,
  'status' : ProjectStatus,
  'created' : Time,
  'name' : IDL.Text,
  'details' : IDL.Text,
  'location' : IDL.Text,
});
export const MarketTrend = IDL.Record({
  'id' : IDL.Text,
  'created' : Time,
  'price' : IDL.Float64,
  'location' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PropertyStatus = IDL.Variant({
  'active' : IDL.Null,
  'disputed' : IDL.Null,
  'pending' : IDL.Null,
  'sold' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Text,
  'status' : PropertyStatus,
  'created' : Time,
  'value' : IDL.Float64,
  'titleNumber' : IDL.Text,
  'owner' : IDL.Principal,
  'area' : IDL.Float64,
  'updated' : Time,
  'location' : IDL.Text,
});
export const PropertyReport = IDL.Record({
  'id' : IDL.Text,
  'created' : Time,
  'content' : IDL.Text,
  'propertyId' : IDL.Text,
  'author' : IDL.Principal,
});
export const SavedProperty = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'propertyId' : IDL.Text,
  'savedAt' : Time,
});
export const TransactionStatus = IDL.Variant({
  'disputed' : IDL.Null,
  'initiated' : IDL.Null,
  'completed' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'date' : Time,
  'propertyId' : IDL.Text,
  'seller' : IDL.Principal,
  'buyer' : IDL.Principal,
  'price' : IDL.Float64,
});
export const ValuationStatus = IDL.Variant({
  'disputed' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const Valuation = IDL.Record({
  'id' : IDL.Text,
  'status' : ValuationStatus,
  'created' : Time,
  'value' : IDL.Float64,
  'date' : Time,
  'valuer' : IDL.Principal,
  'propertyId' : IDL.Text,
});
export const GeneratedPropertyReport = IDL.Record({
  'content' : IDL.Text,
  'generatedAt' : IDL.Int,
  'reportId' : IDL.Text,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const PricePoint = IDL.Record({
  'timestamp' : Time,
  'price' : IDL.Float64,
});
export const MarketTrendData = IDL.Record({
  'demandScore' : IDL.Nat,
  'priceTrend' : IDL.Vec(PricePoint),
  'location' : IDL.Text,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Text,
  'initiator' : IDL.Principal,
  'actionType' : IDL.Text,
  'entityId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
});
export const RiskType = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const BudgetRange = IDL.Record({
  'minBudget' : IDL.Float64,
  'maxBudget' : IDL.Float64,
});
export const Preferences = IDL.Record({
  'notifyInfrastructureUpdates' : IDL.Bool,
  'riskTolerance' : RiskType,
  'notifyNewListings' : IDL.Bool,
  'notifyPriceDrops' : IDL.Bool,
  'aiPersonalization' : IDL.Record({
    'growthExpectation' : IDL.Nat,
    'preferredLandType' : IDL.Text,
    'riskAppetite' : RiskType,
    'investmentGoals' : IDL.Vec(IDL.Text),
    'budgetRange' : BudgetRange,
  }),
  'notifyMarketTrends' : IDL.Bool,
  'notifyDisputes' : IDL.Bool,
  'preferredRegions' : IDL.Vec(IDL.Text),
});
export const AccountStatus = IDL.Variant({
  'pendingVerification' : IDL.Null,
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'suspended' : IDL.Null,
});
export const DomainRole = IDL.Variant({
  'admin' : IDL.Null,
  'citizen' : IDL.Null,
  'landOfficer' : IDL.Null,
});
export const IdentityFields = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'nationalId' : IDL.Text,
  'ethnicity' : IDL.Text,
  'passportNumber' : IDL.Text,
});
export const VerifiedUserProfile = IDL.Record({
  'accountStatus' : AccountStatus,
  'emailVerified' : IDL.Bool,
  'name' : IDL.Text,
  'role' : DomainRole,
  'riskType' : RiskType,
  'identityFields' : IDL.Opt(IdentityFields),
  'idDocument' : IDL.Opt(ExternalBlob),
  'photo' : IDL.Opt(ExternalBlob),
  'phoneVerified' : IDL.Bool,
});
export const NotificationPreferences = IDL.Record({
  'sms' : IDL.Bool,
  'push' : IDL.Bool,
  'criticalAlertsOnly' : IDL.Bool,
  'email' : IDL.Bool,
});
export const ThemePreference = IDL.Variant({
  'dark' : IDL.Null,
  'futuristic' : IDL.Null,
  'light' : IDL.Null,
});
export const PrivacyPreferences = IDL.Record({
  'allowDataCollection' : IDL.Bool,
  'shareLocation' : IDL.Bool,
  'showPublicProfile' : IDL.Bool,
});
export const MotionPreference = IDL.Variant({
  'advanced' : IDL.Null,
  'default' : IDL.Null,
  'reduced' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'notifications' : NotificationPreferences,
  'themePreference' : ThemePreference,
  'privacy' : PrivacyPreferences,
  'motionPreference' : MotionPreference,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});
export const Conversation = IDL.Record({
  'id' : IDL.Text,
  'participantA' : IDL.Principal,
  'participantB' : IDL.Principal,
  'lastMessageTimestamp' : IDL.Int,
  'messages' : IDL.Vec(Message),
});
export const ConversationSummary = IDL.Record({
  'id' : IDL.Text,
  'participantA' : IDL.Principal,
  'participantB' : IDL.Principal,
  'lastMessageTimestamp' : IDL.Int,
  'unreadMessagesCount' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'activeDisputes' : IDL.Nat,
  'recentApplications' : IDL.Vec(
    IDL.Record({
      'id' : IDL.Text,
      'status' : IDL.Text,
      'created' : IDL.Int,
      'titleNumber' : IDL.Text,
    })
  ),
  'verifiedOwners' : IDL.Nat,
  'estimatedTotalLandValue' : IDL.Float64,
  'totalRegisteredTitles' : IDL.Nat,
  'pendingTransactions' : IDL.Nat,
});
export const DemandHeatMapPoint = IDL.Record({
  'demandScore' : IDL.Nat,
  'location' : IDL.Text,
  'coordinates' : IDL.Opt(Coordinates),
});
export const DisputeEvidence = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileId' : IDL.Text,
  'timestamp' : IDL.Int,
  'uploadedBy' : IDL.Principal,
  'disputeId' : IDL.Text,
});
export const DisputeTimelineEvent = IDL.Record({
  'id' : IDL.Text,
  'initiator' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventType' : IDL.Text,
  'disputeId' : IDL.Text,
  'evidenceIds' : IDL.Vec(IDL.Text),
});
export const InfrastructureTimelineItem = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'status' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'impactRadius' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const PortfolioSummary = IDL.Record({
  'riskDistribution' : IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'medium' : IDL.Nat,
  }),
  'annualGrowthRate' : IDL.Float64,
  'totalEstimatedValue' : IDL.Float64,
  'properties' : IDL.Vec(Property),
});
export const MarketAnalytics = IDL.Record({
  'pricesByRegion' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'activeListings' : IDL.Nat,
  'appreciationRates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'topRegions' : IDL.Vec(IDL.Text),
});
export const MarketSummary = IDL.Record({
  'numTransactions' : IDL.Nat,
  'averagePrice' : IDL.Float64,
  'location' : IDL.Text,
});
export const NotificationFeedItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'read' : IDL.Bool,
  'type' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const RiskSummary = IDL.Record({
  'fraudAlertCount' : IDL.Nat,
  'highRiskProperties' : IDL.Vec(IDL.Text),
  'recentDisputes' : IDL.Vec(DisputeView),
  'riskScore' : IDL.Float64,
});
export const VerificationStatus = IDL.Variant({
  'pendingReview' : IDL.Null,
  'verified' : IDL.Null,
  'unverified' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VerificationRecord = IDL.Record({
  'status' : VerificationStatus,
  'officerId' : IDL.Principal,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const TransactionStage = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'recorded' : IDL.Null,
  'stampDuty' : IDL.Null,
  'proposed' : IDL.Null,
  'escrow' : IDL.Null,
});
export const TransactionStageEntry = IDL.Record({
  'initiator' : IDL.Principal,
  'stage' : TransactionStage,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SendMessageResponse = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addDisputeEvidence' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'advanceTransactionStage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveApplication' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateInvestment' : IDL.Func([InvestmentInput], [InvestmentResult], []),
  'calculateValuation' : IDL.Func(
      [ValuationInput],
      [IDL.Variant({ 'ok' : ValuationResult, 'err' : IDL.Text })],
      [],
    ),
  'cancelApplication' : IDL.Func([IDL.Text], [], []),
  'checkApplicationStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LandApplicationView)],
      [],
    ),
  'clearCallerPreferences' : IDL.Func([], [], []),
  'clearSearchCounts' : IDL.Func([], [], []),
  'clearUserSettings' : IDL.Func([], [], []),
  'createApplication' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDispute' : IDL.Func([DisputeView], [], []),
  'createInfrastructureProject' : IDL.Func([InfrastructureProject], [], []),
  'createMarketTrend' : IDL.Func([MarketTrend], [], []),
  'createNotification' : IDL.Func([Notification], [], []),
  'createProperty' : IDL.Func([Property], [], []),
  'createPropertyReport' : IDL.Func([PropertyReport], [], []),
  'createSavedProperty' : IDL.Func([SavedProperty], [], []),
  'createTransaction' : IDL.Func([Transaction], [], []),
  'createValuation' : IDL.Func([Valuation], [], []),
  'deleteConversation' : IDL.Func([IDL.Text], [], []),
  'deleteDispute' : IDL.Func([IDL.Text], [], []),
  'deleteInfrastructureProject' : IDL.Func([IDL.Text], [], []),
  'deleteMarketTrend' : IDL.Func([IDL.Text], [], []),
  'deleteNotification' : IDL.Func([IDL.Text], [], []),
  'deleteProperty' : IDL.Func([IDL.Text], [], []),
  'deletePropertyReport' : IDL.Func([IDL.Text], [], []),
  'deleteSavedProperty' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [], []),
  'deleteValuation' : IDL.Func([IDL.Text], [], []),
  'exportAuditCsv' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Text], []),
  'generatePropertyReport' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : GeneratedPropertyReport, 'err' : IDL.Text })],
      [],
    ),
  'getAllCoordinates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Coordinates))],
      ['query'],
    ),
  'getAllMarketTrends' : IDL.Func([], [IDL.Vec(MarketTrendData)], ['query']),
  'getApplicationStatus' : IDL.Func([IDL.Text], [ApplicationStatus], ['query']),
  'getApplications' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(LandApplicationView)],
      [],
    ),
  'getApplicationsByStatusInternal' : IDL.Func(
      [ApplicationStatus],
      [IDL.Vec(LandApplicationView)],
      ['query'],
    ),
  'getAuditLog' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Vec(AuditEntry)],
      [],
    ),
  'getCallerPreferences' : IDL.Func([], [Preferences], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(VerifiedUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getConversationMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], []),
  'getDemandHeatMapPoints' : IDL.Func(
      [],
      [IDL.Vec(DemandHeatMapPoint)],
      ['query'],
    ),
  'getDemandScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getDispute' : IDL.Func([IDL.Text], [IDL.Opt(DisputeView)], ['query']),
  'getDisputeEvidence' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(DisputeEvidence), 'err' : IDL.Text })],
      [],
    ),
  'getDisputeTimeline' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(DisputeTimelineEvent), 'err' : IDL.Text })],
      [],
    ),
  'getInfrastructureProject' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(InfrastructureProject)],
      ['query'],
    ),
  'getInfrastructureTimeline' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(InfrastructureTimelineItem)],
      [],
    ),
  'getInvestmentPortfolioSummary' : IDL.Func([], [PortfolioSummary], []),
  'getLocationCoordinates' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Coordinates)],
      ['query'],
    ),
  'getMarketAnalytics' : IDL.Func([IDL.Opt(IDL.Text)], [MarketAnalytics], []),
  'getMarketSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MarketSummary)],
      ['query'],
    ),
  'getMarketTrend' : IDL.Func([IDL.Text], [IDL.Opt(MarketTrend)], ['query']),
  'getMarketplaceListings' : IDL.Func(
      [IDL.Opt(IDL.Bool), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64)],
      [IDL.Vec(Property)],
      [],
    ),
  'getNotification' : IDL.Func([IDL.Text], [IDL.Opt(Notification)], ['query']),
  'getNotificationFeed' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(NotificationFeedItem)],
      [],
    ),
  'getPriceTrend' : IDL.Func([IDL.Text], [IDL.Vec(PricePoint)], ['query']),
  'getProperty' : IDL.Func([IDL.Text], [IDL.Opt(Property)], ['query']),
  'getPropertyReport' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PropertyReport)],
      ['query'],
    ),
  'getRiskIntelligenceSummary' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [RiskSummary],
      [],
    ),
  'getSavedProperty' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SavedProperty)],
      ['query'],
    ),
  'getTitleVerificationHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(VerificationRecord), 'err' : IDL.Text })],
      [],
    ),
  'getTopSearches' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
  'getTransactionStageHistory' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Vec(TransactionStageEntry),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getUserConversations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getUserPreferences' : IDL.Func([IDL.Principal], [Preferences], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(VerifiedUserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([IDL.Principal], [UserSettings], ['query']),
  'getValuation' : IDL.Func([IDL.Text], [IDL.Opt(Valuation)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDisputes' : IDL.Func([], [IDL.Vec(DisputeView)], ['query']),
  'listInfrastructureProjects' : IDL.Func(
      [],
      [IDL.Vec(InfrastructureProject)],
      ['query'],
    ),
  'listMarketTrends' : IDL.Func([], [IDL.Vec(MarketTrend)], ['query']),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'listPropertyReports' : IDL.Func([], [IDL.Vec(PropertyReport)], ['query']),
  'listSavedProperties' : IDL.Func([], [IDL.Vec(SavedProperty)], ['query']),
  'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'listValuations' : IDL.Func([], [IDL.Vec(Valuation)], ['query']),
  'markAllMessagesAsRead' : IDL.Func([IDL.Text], [], []),
  'markNotificationRead' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'officerVerifyTitle' : IDL.Func(
      [IDL.Text, VerificationStatus, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordSearch' : IDL.Func([IDL.Text], [], []),
  'rejectApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([VerifiedUserProfile], [], []),
  'searchApplicationByTitleNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LandApplicationView)],
      [],
    ),
  'searchApplicationsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LandApplicationView)],
      ['query'],
    ),
  'searchApplicationsByTitleNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LandApplicationView)],
      ['query'],
    ),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, VerifiedUserProfile))],
      ['query'],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [SendMessageResponse],
      [],
    ),
  'setCallerPreferences' : IDL.Func([Preferences], [], []),
  'setDemandScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setLocationCoordinates' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'setMarketSummary' : IDL.Func([IDL.Text, MarketSummary], [], []),
  'setPriceTrend' : IDL.Func([IDL.Text, IDL.Vec(PricePoint)], [], []),
  'submitApplication' : IDL.Func([IDL.Text], [], []),
  'submitForVerification' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCallerUserSettings' : IDL.Func([UserSettings], [UserSettings], []),
  'updateDispute' : IDL.Func([DisputeView], [], []),
  'updateInfrastructureProject' : IDL.Func([InfrastructureProject], [], []),
  'updateMarketTrend' : IDL.Func([MarketTrend], [], []),
  'updateNotification' : IDL.Func([Notification], [], []),
  'updateProperty' : IDL.Func([Property], [], []),
  'updatePropertyReport' : IDL.Func([PropertyReport], [], []),
  'updateSavedProperty' : IDL.Func([SavedProperty], [], []),
  'updateTransaction' : IDL.Func([Transaction], [], []),
  'updateValuation' : IDL.Func([Valuation], [], []),
  'uploadAttachment' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvestmentInput = IDL.Record({
    'investmentYears' : IDL.Nat,
    'buyingPriceKES' : IDL.Float64,
    'annualGrowthRatePercent' : IDL.Float64,
  });
  const InvestmentResult = IDL.Record({
    'profitKES' : IDL.Float64,
    'projectedValueKES' : IDL.Float64,
    'roiPercent' : IDL.Float64,
    'breakEvenYears' : IDL.Float64,
    'profitPercent' : IDL.Float64,
  });
  const ValuationInput = IDL.Record({
    'roadAccess' : IDL.Bool,
    'landSizeAcres' : IDL.Float64,
    'nearbyAmenities' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const ValuationResult = IDL.Record({
    'comparableProperties' : IDL.Vec(IDL.Text),
    'growthForecastPercent' : IDL.Float64,
    'confidenceScore' : IDL.Float64,
    'estimatedValueKES' : IDL.Float64,
    'investmentPotential' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'submitted' : IDL.Null,
    'underReview' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LandApplicationView = IDL.Record({
    'id' : IDL.Text,
    'status' : ApplicationStatus,
    'created' : Time,
    'titleNumber' : IDL.Text,
    'owner' : IDL.Principal,
    'area' : IDL.Opt(IDL.Nat),
    'updated' : Time,
    'location' : IDL.Text,
    'attachments' : IDL.Vec(ExternalBlob),
  });
  const DisputeStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'underReview' : IDL.Null,
    'open' : IDL.Null,
  });
  const DisputeView = IDL.Record({
    'id' : IDL.Text,
    'status' : DisputeStatus,
    'created' : Time,
    'initiator' : IDL.Principal,
    'propertyId' : IDL.Text,
    'updated' : Time,
    'comments' : IDL.Vec(IDL.Text),
    'reason' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const InfrastructureProject = IDL.Record({
    'id' : IDL.Text,
    'status' : ProjectStatus,
    'created' : Time,
    'name' : IDL.Text,
    'details' : IDL.Text,
    'location' : IDL.Text,
  });
  const MarketTrend = IDL.Record({
    'id' : IDL.Text,
    'created' : Time,
    'price' : IDL.Float64,
    'location' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PropertyStatus = IDL.Variant({
    'active' : IDL.Null,
    'disputed' : IDL.Null,
    'pending' : IDL.Null,
    'sold' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Text,
    'status' : PropertyStatus,
    'created' : Time,
    'value' : IDL.Float64,
    'titleNumber' : IDL.Text,
    'owner' : IDL.Principal,
    'area' : IDL.Float64,
    'updated' : Time,
    'location' : IDL.Text,
  });
  const PropertyReport = IDL.Record({
    'id' : IDL.Text,
    'created' : Time,
    'content' : IDL.Text,
    'propertyId' : IDL.Text,
    'author' : IDL.Principal,
  });
  const SavedProperty = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'propertyId' : IDL.Text,
    'savedAt' : Time,
  });
  const TransactionStatus = IDL.Variant({
    'disputed' : IDL.Null,
    'initiated' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'date' : Time,
    'propertyId' : IDL.Text,
    'seller' : IDL.Principal,
    'buyer' : IDL.Principal,
    'price' : IDL.Float64,
  });
  const ValuationStatus = IDL.Variant({
    'disputed' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Valuation = IDL.Record({
    'id' : IDL.Text,
    'status' : ValuationStatus,
    'created' : Time,
    'value' : IDL.Float64,
    'date' : Time,
    'valuer' : IDL.Principal,
    'propertyId' : IDL.Text,
  });
  const GeneratedPropertyReport = IDL.Record({
    'content' : IDL.Text,
    'generatedAt' : IDL.Int,
    'reportId' : IDL.Text,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const PricePoint = IDL.Record({ 'timestamp' : Time, 'price' : IDL.Float64 });
  const MarketTrendData = IDL.Record({
    'demandScore' : IDL.Nat,
    'priceTrend' : IDL.Vec(PricePoint),
    'location' : IDL.Text,
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Text,
    'initiator' : IDL.Principal,
    'actionType' : IDL.Text,
    'entityId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
  });
  const RiskType = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const BudgetRange = IDL.Record({
    'minBudget' : IDL.Float64,
    'maxBudget' : IDL.Float64,
  });
  const Preferences = IDL.Record({
    'notifyInfrastructureUpdates' : IDL.Bool,
    'riskTolerance' : RiskType,
    'notifyNewListings' : IDL.Bool,
    'notifyPriceDrops' : IDL.Bool,
    'aiPersonalization' : IDL.Record({
      'growthExpectation' : IDL.Nat,
      'preferredLandType' : IDL.Text,
      'riskAppetite' : RiskType,
      'investmentGoals' : IDL.Vec(IDL.Text),
      'budgetRange' : BudgetRange,
    }),
    'notifyMarketTrends' : IDL.Bool,
    'notifyDisputes' : IDL.Bool,
    'preferredRegions' : IDL.Vec(IDL.Text),
  });
  const AccountStatus = IDL.Variant({
    'pendingVerification' : IDL.Null,
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const DomainRole = IDL.Variant({
    'admin' : IDL.Null,
    'citizen' : IDL.Null,
    'landOfficer' : IDL.Null,
  });
  const IdentityFields = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'nationalId' : IDL.Text,
    'ethnicity' : IDL.Text,
    'passportNumber' : IDL.Text,
  });
  const VerifiedUserProfile = IDL.Record({
    'accountStatus' : AccountStatus,
    'emailVerified' : IDL.Bool,
    'name' : IDL.Text,
    'role' : DomainRole,
    'riskType' : RiskType,
    'identityFields' : IDL.Opt(IdentityFields),
    'idDocument' : IDL.Opt(ExternalBlob),
    'photo' : IDL.Opt(ExternalBlob),
    'phoneVerified' : IDL.Bool,
  });
  const NotificationPreferences = IDL.Record({
    'sms' : IDL.Bool,
    'push' : IDL.Bool,
    'criticalAlertsOnly' : IDL.Bool,
    'email' : IDL.Bool,
  });
  const ThemePreference = IDL.Variant({
    'dark' : IDL.Null,
    'futuristic' : IDL.Null,
    'light' : IDL.Null,
  });
  const PrivacyPreferences = IDL.Record({
    'allowDataCollection' : IDL.Bool,
    'shareLocation' : IDL.Bool,
    'showPublicProfile' : IDL.Bool,
  });
  const MotionPreference = IDL.Variant({
    'advanced' : IDL.Null,
    'default' : IDL.Null,
    'reduced' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'notifications' : NotificationPreferences,
    'themePreference' : ThemePreference,
    'privacy' : PrivacyPreferences,
    'motionPreference' : MotionPreference,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Text,
    'participantA' : IDL.Principal,
    'participantB' : IDL.Principal,
    'lastMessageTimestamp' : IDL.Int,
    'messages' : IDL.Vec(Message),
  });
  const ConversationSummary = IDL.Record({
    'id' : IDL.Text,
    'participantA' : IDL.Principal,
    'participantB' : IDL.Principal,
    'lastMessageTimestamp' : IDL.Int,
    'unreadMessagesCount' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'activeDisputes' : IDL.Nat,
    'recentApplications' : IDL.Vec(
      IDL.Record({
        'id' : IDL.Text,
        'status' : IDL.Text,
        'created' : IDL.Int,
        'titleNumber' : IDL.Text,
      })
    ),
    'verifiedOwners' : IDL.Nat,
    'estimatedTotalLandValue' : IDL.Float64,
    'totalRegisteredTitles' : IDL.Nat,
    'pendingTransactions' : IDL.Nat,
  });
  const DemandHeatMapPoint = IDL.Record({
    'demandScore' : IDL.Nat,
    'location' : IDL.Text,
    'coordinates' : IDL.Opt(Coordinates),
  });
  const DisputeEvidence = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileId' : IDL.Text,
    'timestamp' : IDL.Int,
    'uploadedBy' : IDL.Principal,
    'disputeId' : IDL.Text,
  });
  const DisputeTimelineEvent = IDL.Record({
    'id' : IDL.Text,
    'initiator' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventType' : IDL.Text,
    'disputeId' : IDL.Text,
    'evidenceIds' : IDL.Vec(IDL.Text),
  });
  const InfrastructureTimelineItem = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'status' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'impactRadius' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const PortfolioSummary = IDL.Record({
    'riskDistribution' : IDL.Record({
      'low' : IDL.Nat,
      'high' : IDL.Nat,
      'medium' : IDL.Nat,
    }),
    'annualGrowthRate' : IDL.Float64,
    'totalEstimatedValue' : IDL.Float64,
    'properties' : IDL.Vec(Property),
  });
  const MarketAnalytics = IDL.Record({
    'pricesByRegion' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'activeListings' : IDL.Nat,
    'appreciationRates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'topRegions' : IDL.Vec(IDL.Text),
  });
  const MarketSummary = IDL.Record({
    'numTransactions' : IDL.Nat,
    'averagePrice' : IDL.Float64,
    'location' : IDL.Text,
  });
  const NotificationFeedItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'read' : IDL.Bool,
    'type' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const RiskSummary = IDL.Record({
    'fraudAlertCount' : IDL.Nat,
    'highRiskProperties' : IDL.Vec(IDL.Text),
    'recentDisputes' : IDL.Vec(DisputeView),
    'riskScore' : IDL.Float64,
  });
  const VerificationStatus = IDL.Variant({
    'pendingReview' : IDL.Null,
    'verified' : IDL.Null,
    'unverified' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VerificationRecord = IDL.Record({
    'status' : VerificationStatus,
    'officerId' : IDL.Principal,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const TransactionStage = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'recorded' : IDL.Null,
    'stampDuty' : IDL.Null,
    'proposed' : IDL.Null,
    'escrow' : IDL.Null,
  });
  const TransactionStageEntry = IDL.Record({
    'initiator' : IDL.Principal,
    'stage' : TransactionStage,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SendMessageResponse = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addDisputeEvidence' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'advanceTransactionStage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveApplication' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateInvestment' : IDL.Func([InvestmentInput], [InvestmentResult], []),
    'calculateValuation' : IDL.Func(
        [ValuationInput],
        [IDL.Variant({ 'ok' : ValuationResult, 'err' : IDL.Text })],
        [],
      ),
    'cancelApplication' : IDL.Func([IDL.Text], [], []),
    'checkApplicationStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LandApplicationView)],
        [],
      ),
    'clearCallerPreferences' : IDL.Func([], [], []),
    'clearSearchCounts' : IDL.Func([], [], []),
    'clearUserSettings' : IDL.Func([], [], []),
    'createApplication' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDispute' : IDL.Func([DisputeView], [], []),
    'createInfrastructureProject' : IDL.Func([InfrastructureProject], [], []),
    'createMarketTrend' : IDL.Func([MarketTrend], [], []),
    'createNotification' : IDL.Func([Notification], [], []),
    'createProperty' : IDL.Func([Property], [], []),
    'createPropertyReport' : IDL.Func([PropertyReport], [], []),
    'createSavedProperty' : IDL.Func([SavedProperty], [], []),
    'createTransaction' : IDL.Func([Transaction], [], []),
    'createValuation' : IDL.Func([Valuation], [], []),
    'deleteConversation' : IDL.Func([IDL.Text], [], []),
    'deleteDispute' : IDL.Func([IDL.Text], [], []),
    'deleteInfrastructureProject' : IDL.Func([IDL.Text], [], []),
    'deleteMarketTrend' : IDL.Func([IDL.Text], [], []),
    'deleteNotification' : IDL.Func([IDL.Text], [], []),
    'deleteProperty' : IDL.Func([IDL.Text], [], []),
    'deletePropertyReport' : IDL.Func([IDL.Text], [], []),
    'deleteSavedProperty' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [], []),
    'deleteValuation' : IDL.Func([IDL.Text], [], []),
    'exportAuditCsv' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Text], []),
    'generatePropertyReport' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : GeneratedPropertyReport, 'err' : IDL.Text })],
        [],
      ),
    'getAllCoordinates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Coordinates))],
        ['query'],
      ),
    'getAllMarketTrends' : IDL.Func([], [IDL.Vec(MarketTrendData)], ['query']),
    'getApplicationStatus' : IDL.Func(
        [IDL.Text],
        [ApplicationStatus],
        ['query'],
      ),
    'getApplications' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(LandApplicationView)],
        [],
      ),
    'getApplicationsByStatusInternal' : IDL.Func(
        [ApplicationStatus],
        [IDL.Vec(LandApplicationView)],
        ['query'],
      ),
    'getAuditLog' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Vec(AuditEntry)],
        [],
      ),
    'getCallerPreferences' : IDL.Func([], [Preferences], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(VerifiedUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getConversationMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], []),
    'getDemandHeatMapPoints' : IDL.Func(
        [],
        [IDL.Vec(DemandHeatMapPoint)],
        ['query'],
      ),
    'getDemandScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getDispute' : IDL.Func([IDL.Text], [IDL.Opt(DisputeView)], ['query']),
    'getDisputeEvidence' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(DisputeEvidence), 'err' : IDL.Text })],
        [],
      ),
    'getDisputeTimeline' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(DisputeTimelineEvent),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getInfrastructureProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InfrastructureProject)],
        ['query'],
      ),
    'getInfrastructureTimeline' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(InfrastructureTimelineItem)],
        [],
      ),
    'getInvestmentPortfolioSummary' : IDL.Func([], [PortfolioSummary], []),
    'getLocationCoordinates' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Coordinates)],
        ['query'],
      ),
    'getMarketAnalytics' : IDL.Func([IDL.Opt(IDL.Text)], [MarketAnalytics], []),
    'getMarketSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MarketSummary)],
        ['query'],
      ),
    'getMarketTrend' : IDL.Func([IDL.Text], [IDL.Opt(MarketTrend)], ['query']),
    'getMarketplaceListings' : IDL.Func(
        [IDL.Opt(IDL.Bool), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64)],
        [IDL.Vec(Property)],
        [],
      ),
    'getNotification' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Notification)],
        ['query'],
      ),
    'getNotificationFeed' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(NotificationFeedItem)],
        [],
      ),
    'getPriceTrend' : IDL.Func([IDL.Text], [IDL.Vec(PricePoint)], ['query']),
    'getProperty' : IDL.Func([IDL.Text], [IDL.Opt(Property)], ['query']),
    'getPropertyReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PropertyReport)],
        ['query'],
      ),
    'getRiskIntelligenceSummary' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [RiskSummary],
        [],
      ),
    'getSavedProperty' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SavedProperty)],
        ['query'],
      ),
    'getTitleVerificationHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(VerificationRecord), 'err' : IDL.Text })],
        [],
      ),
    'getTopSearches' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
    'getTransactionStageHistory' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(TransactionStageEntry),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getUserConversations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getUserPreferences' : IDL.Func([IDL.Principal], [Preferences], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(VerifiedUserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([IDL.Principal], [UserSettings], ['query']),
    'getValuation' : IDL.Func([IDL.Text], [IDL.Opt(Valuation)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDisputes' : IDL.Func([], [IDL.Vec(DisputeView)], ['query']),
    'listInfrastructureProjects' : IDL.Func(
        [],
        [IDL.Vec(InfrastructureProject)],
        ['query'],
      ),
    'listMarketTrends' : IDL.Func([], [IDL.Vec(MarketTrend)], ['query']),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'listPropertyReports' : IDL.Func([], [IDL.Vec(PropertyReport)], ['query']),
    'listSavedProperties' : IDL.Func([], [IDL.Vec(SavedProperty)], ['query']),
    'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'listValuations' : IDL.Func([], [IDL.Vec(Valuation)], ['query']),
    'markAllMessagesAsRead' : IDL.Func([IDL.Text], [], []),
    'markNotificationRead' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'officerVerifyTitle' : IDL.Func(
        [IDL.Text, VerificationStatus, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordSearch' : IDL.Func([IDL.Text], [], []),
    'rejectApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([VerifiedUserProfile], [], []),
    'searchApplicationByTitleNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LandApplicationView)],
        [],
      ),
    'searchApplicationsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LandApplicationView)],
        ['query'],
      ),
    'searchApplicationsByTitleNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LandApplicationView)],
        ['query'],
      ),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, VerifiedUserProfile))],
        ['query'],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [SendMessageResponse],
        [],
      ),
    'setCallerPreferences' : IDL.Func([Preferences], [], []),
    'setDemandScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setLocationCoordinates' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setMarketSummary' : IDL.Func([IDL.Text, MarketSummary], [], []),
    'setPriceTrend' : IDL.Func([IDL.Text, IDL.Vec(PricePoint)], [], []),
    'submitApplication' : IDL.Func([IDL.Text], [], []),
    'submitForVerification' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCallerUserSettings' : IDL.Func([UserSettings], [UserSettings], []),
    'updateDispute' : IDL.Func([DisputeView], [], []),
    'updateInfrastructureProject' : IDL.Func([InfrastructureProject], [], []),
    'updateMarketTrend' : IDL.Func([MarketTrend], [], []),
    'updateNotification' : IDL.Func([Notification], [], []),
    'updateProperty' : IDL.Func([Property], [], []),
    'updatePropertyReport' : IDL.Func([PropertyReport], [], []),
    'updateSavedProperty' : IDL.Func([SavedProperty], [], []),
    'updateTransaction' : IDL.Func([Transaction], [], []),
    'updateValuation' : IDL.Func([Valuation], [], []),
    'uploadAttachment' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };